chore: remove hardcoded constants for ids
influxdata/influxdb pull request #19548
Opened 2020-09-10 19:36 UTC by yquansah

Closes #

Describe your proposed changes here.

Description of issue and what this PR seeks to achieve are detailed within this issue: https://github.com/influxdata/influxdb/issues/19547

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [ ] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [ ] Rebased/mergeable
- [ ] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Feature flagged (if modified API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

2020-09-10 21:17 UTC, stuartcarnie requested changes
Apologies if my issue was lacking some clarity, @yquansah! 

Previously, these system buckets did not exist in the key/value store, as we had hard coded them with IDs `10` and `11`. All the routines to read buckets had to manually materialize them. We have since made them real data in the key/value store, so these routines will fetch them as expected by reading the data from the key/value store.

2020-09-10 21:17 UTC, stuartcarnie commented on kv/bucket.go
>  				RetentionPeriod: influxdb.TasksSystemBucketRetention,
This entire switch statement can be deleted and the `if IsNotFound(err)` statement only needs to return the `default` case:

```go
return nil, &influxdb.Error{
    Code: influxdb.ENotFound,
    Msg:  fmt.Sprintf("bucket %q not found", n),
}
```

2020-09-10 21:17 UTC, stuartcarnie commented on kv/bucket.go
>  	if needsSystemBuckets {
Here is also legacy, so everything from:

```go
needsSystemBuckets := true
for _, b := range bs {
```

through to line 382 can be deleted.

2020-09-10 21:17 UTC, stuartcarnie commented on tenant/storage_bucket.go
>  		switch n {
Same for this one, the `if kv.IsNotFound(err) {` need only be `return nil, ErrBucketNotFoundByName(n)` as the fixed system buckets are gone.

2020-09-11 19:28 UTC, yquansah commented
@stuartcarnie Excellent. Where does the logic live that stores these system buckets in key/value store? (Hopefully I am not misunderstanding)

2020-09-11 19:37 UTC, stuartcarnie commented
Fair question, @yquansah. These are created automatically when an organization is created, and exist as real metadata in the key/value store:

https://github.com/influxdata/influxdb/blob/45a3f2e87c90c2e2d3fbeaae9a800aaa556c46ac/kv/bucket.go#L136-L156

We then look these buckets up by `name` to find them.

2020-09-11 19:41 UTC, stuartcarnie approved these changes
Great cleanup, @yquansah 🧹

2020-09-14 16:20 UTC, merged