feat(upgrade): upgrade database
influxdata/influxdb pull request #19642
Opened 2020-09-25 15:28 UTC by vlastahajek

This is 2nd PR of 4  for the upgrade feature.
Adds creating of the admin user and upgrading database logic.

- [X] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [X] Rebased/mergeable
- [X] Tests pass

2020-09-25 15:34 UTC, vlastahajek commented
It ready for comments, but I keep it in the draft,  cause I'm going to extend tests for db upgrade a bit.

2020-10-06 00:23 UTC, stuartcarnie requested changes
Looking good! 

Can you verify that `goimports` has been run across all the files, as I noticed some inconsistencies in formatting.

2020-10-06 00:23 UTC, stuartcarnie commented on cmd/influxd/upgrade/fs.go
> +// dirRenameFunc allows renaming  directories. It must return orig name, if renaming is not done..
```suggestion
// dirRenameFunc is a mapping function that transforms path to a new name. Returning the path specifies the directory should not be renamed.
```

2020-10-06 00:23 UTC, stuartcarnie commented on cmd/influxd/upgrade/fs.go
> +// dirFilterFunc allows filtering out directories. Returned true means skipping the dir.
```suggestion
// dirFilterFunc ignores all directories where dirFilterFunc(path) is true. Passing nil for dirFilterFunc includes all directories.
```

2020-10-06 00:23 UTC, stuartcarnie commented on cmd/influxd/upgrade/fs.go
> +// fileFilterFunc allows filtering out files. Returned true means skipping the file.
```suggestion
// fileFilterFunc ignores all files where fileFilterFunc(path) is true. Passing nil for fileFilterFunc includes all files.
```

2020-10-06 00:23 UTC, stuartcarnie commented on pkg/fs/fs.go
> +}
We already have a dependency on the https://github.com/dustin/go-humanize package, so you should be able to use `humanize.Bytes`:

https://pkg.go.dev/github.com/dustin/go-humanize#Bytes

2020-10-06 00:23 UTC, stuartcarnie commented on pkg/fs/fs_unix.go
> +	syscall2 "golang.org/x/sys/unix"
This should be imported as `unix`

2020-10-06 07:03 UTC, vlastahajek commented on cmd/influxd/upgrade/database.go
> +	if options.verbose {
Ok

2020-10-06 08:10 UTC, vlastahajek commented on cmd/influxd/upgrade/database.go
> +	fs2 "github.com/influxdata/influxdb/v2/pkg/fs"
No. The local fs.go was previously in the `upgrade/fs` package and it was imported as `fs`. After moving to the same folder, `pkg/fs` stayed as `fs2`.

2020-10-06 08:26 UTC, vlastahajek commented on cmd/influxd/upgrade/database.go
> +			continue
Good point! 👍 
I wasn't sure if there could be other internal databases, that would also start with '_'. But after testing with 1.8.1 I see user can create a database starting with '_'.

2020-10-06 10:47 UTC, vlastahajek commented on cmd/influxd/launcher/launcher_helpers.go
> +	RealServer bool
Ok

2020-10-07 01:03 UTC, stuartcarnie commented on cmd/influxd/upgrade/database.go
> +	if options.verbose {
Ok, that is great – my intent is that `verbose` is the default option if the user does not specify anything.

2020-10-07 01:06 UTC, stuartcarnie approved these changes
Great! We're good to go with this one too 👏 👏

2020-10-07 01:06 UTC, stuartcarnie commented on cmd/influxd/launcher/launcher_helpers.go
> +
👏

2020-10-08 16:39 UTC, merged