feat(cli): Extend CLI with v1 authorization commands
influxdata/influxdb pull request #19829
Opened 2020-10-27 00:32 UTC by stuartcarnie

Closes #19765

This commit add a series of new subcommands to the `influx` CLI tool. The specific commands are:

* `influx v1` to host any InfluxDB v1 specific commands
* `influx v1 auth` for v1 authorization token management.

The `v1 auth` commands enable access to the private authorization APIs (see #19815) used to manage authorization tokens for v1 compatibility APIs, including:

* `/write`
* `/query`

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [ ] Tests pass

2020-10-27 00:33 UTC, stuartcarnie commented
@gavincabbage the team-assigner gods picked you!

2020-10-27 15:48 UTC, stuartcarnie commented
@gavincabbage I'll request a review when this is ready, as we need to make a few additional changes

2020-10-28 22:22 UTC, stuartcarnie commented
@gavincabbage this PR is ready for review

2020-10-29 12:31 UTC, gavincabbage requested changes
Looks good Stuart- just wanted to ask, would it be appropriate to add some tests for all the business logic in `v1_authorization.go`?

2020-10-29 14:56 UTC, stuartcarnie commented
> would it be appropriate to add some tests for all the business logic in `v1_authorization.go`?

I'm not really sure we have established a way to test CLI commands and I don't see precedent for testing any of the other ones. We do test the HTTP APIs that the CLI commands call, however.

2020-10-29 14:57 UTC, stuartcarnie commented
Well, it looks like `bucket` has some tests:

https://github.com/influxdata/influxdb/blob/6bc4158a46f61897a2796c841958c8b74ed424fd/cmd/influx/bucket_test.go#L33

2020-10-29 14:58 UTC, stuartcarnie commented
I'll take a closer look at the bucket tests and verify what they are testing – if they add value, I'll do the same.

2020-10-29 15:19 UTC, stuartcarnie commented
@gavincabbage I'm going to add a follow up task to investigate refactoring these commands so they are testable. 

The v1_authorization command was copied from `authorization.go` and is not testable, as the dependencies are not injected.

2020-10-29 15:20 UTC, gavincabbage approved these changes
Great, sounds good @stuartcarnie. I just made a similar call to skip testing something difficult to test until I refactor it to make it testable, so I know how that goes 😅

2020-10-29 15:21 UTC, merged