fix(http): Add same site strict flag to session cookie
influxdata/influxdb pull request #20015
Opened 2020-11-12 23:00 UTC by pierwill

- [ ] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [ ] Rebased/mergeable
- [ ] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Feature flagged (if modified API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

2020-11-12 23:32 UTC, glinton requested changes
Somewhere in this pr, it would be great to document why strict mode was chosen over lax.

2020-11-12 23:32 UTC, glinton commented on http/session_handler.go
> +		SameSite: 3, // SameSiteStrictMode
Rather than using the number, use the self-documenting variable.
```suggestion
		SameSite: http.SameSiteStrictMode,
```

2020-11-13 00:00 UTC, glinton approved these changes
I'd still say document why you chose "strict" over "lax" for posterity's sake (ideally it would be configurable to suit individual user's needs :thinking:)

2020-11-13 00:25 UTC, pierwill commented
Using "strict" here because it is more restrictive.

2020-11-13 19:58 UTC, merged