fix(tsdb): never use an inmem index
influxdata/influxdb pull request #20313
Opened 2020-12-11 15:31 UTC by danxmoran

Closes #20257 

2.x was never meant to use an inmem index, but there was a fallback code path to handle cases when `influxd upgrade` didn't convert an inmem index into TSI. All code for the inmem index is now deleted, and the fallback is replaced by a one-time reindex operation run on shards w/o a TSI directory.

The reindex logic is inspired by the [`influx inspect` implementation](https://github.com/influxdata/influxdb/blob/master/cmd/influx_inspect/buildtsi/buildtsi.go#L341), but uses methods on `Engine` to read TSM / WAL data instead of listing and reading files directly from the file system.

2020-12-11 22:05 UTC, danxmoran commented
@stuartcarnie could you take a look at this one? I'm pretty confident the existing gotests cover the logic (many were failing when I still had bugs in `Reindex()`), but I'm not familiar enough with the code to be 100% sure.

2020-12-14 22:12 UTC, dgnorton requested changes

2020-12-14 22:36 UTC, danxmoran commented
Other note from Zoom review: try to add an integration test to check that index files are (re)generated if missing, and that query results are the same.

2020-12-14 22:43 UTC, danxmoran commented on tsdb/engine/tsm1/engine.go
> +			names[i], tags[i] = models.ParseKeyBytesWithTags(seriesKeys[i], tags[i])
Noticed while removing the log line below... the `tags[i]` arg to `ParseKeyBytesWithTags` is fishy...

2020-12-14 22:50 UTC, danxmoran commented on tsdb/engine/tsm1/engine.go
> +			)
Didn't see a Trace() option, so I'll move this out of the loop and have it instead debug-log the size of the batch being indexed.

2020-12-14 23:05 UTC, danxmoran commented on tsdb/engine/tsm1/engine.go
> +			)
Hmmm actually, looks like there is a trace logger in the engine struct. Will look into using both logs.

2020-12-16 18:23 UTC, danxmoran commented on tsdb/shard_test.go
> +	// and ensure that we can still write data
Before merge: also need to check that the index dir has been re-written.

2020-12-22 20:57 UTC, danxmoran commented on storage/engine.go
> +		pw.WithLogger(e.logger)
Drive-by fix for engine logging setup

2020-12-23 00:37 UTC, stuartcarnie approved these changes
Great work, @danxmoran – removing this will simplify future maintenance of the TSDB engine. 🥇 👏 🧹

2020-12-23 15:46 UTC, merged