refactor: do not use context value anti-pattern
influxdata/influxdb pull request #20664
Opened 2021-02-01 19:21 UTC by lesam

Extending the context instead of fixing the API breaks type safety.
For tracking the number of points / values written, it is much clearer
to pass an explicit tracker.

https://github.com/influxdata/influxdb/pull/19445

- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

2021-02-01 19:25 UTC, lesam commented on tsdb/shard.go
> +	engineTracker := func (points, values int64){
This will likely cause an allocation per shard per write request - not too worried about that performance wise, thoughts from @dgnorton ?

2021-02-01 19:34 UTC, lesam commented
Ran go imports

2021-02-01 19:35 UTC, lesam commented on tsdb/shard.go
> +	}
Note this re: performance

2021-02-01 20:18 UTC, dgnorton approved these changes

2021-02-02 13:33 UTC, lesam commented
New style:

```
"localStore": {"name":"localStore","tags":null,"values":{"pointWrite":2319,"valueWrite":18396}},
"write": {"name":"write","tags":null,"values":{"pointReq":2319,"pointReqLocal":2319,"req":4,"subWriteDrop":0,"subWriteOk":4,"writeDrop":0,"writeError":0,"writeOk":4,"writeTimeout":0}},
```

Full output attached

2021-02-02 15:49 UTC, dgnorton approved these changes

2021-02-02 15:54 UTC, dgnorton requested changes
@lesam can we change `pointWrite` and `valueWrite` to match the others? `pointsWritten` and `valuesWritten`

2021-02-02 16:02 UTC, lesam commented
> @lesam can we change `pointWrite` and `valueWrite` to match the others? `pointsWritten` and `valuesWritten`

Done

2021-02-02 16:04 UTC, dgnorton approved these changes

2021-02-02 16:12 UTC, merged