fix(flux): add durations to Flux logging (#19697)
influxdata/influxdb pull request #20940
Opened 2021-03-12 20:54 UTC by lesam

(cherry picked from commit 25fb1077e2dd5469e7a3055db76fc71a99e95139)

Closes #

Describe your proposed changes here.

- [ ] [CHANGELOG.md](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) updated with a link to the PR (not the Issue)
- [ ] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [ ] Rebased/mergeable
- [ ] Tests pass
- [ ] http/swagger.yml updated (if modified Go structs or API)
- [ ] Feature flagged (if modified API)
- [ ] Documentation updated or issue created (provide link to issue/pr)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

2021-03-12 21:15 UTC, davidby-influx requested changes
Looks like some errors, noted in the comments.

2021-03-12 21:15 UTC, davidby-influx commented on flux/control/controller.go
> +<<<<<<< HEAD
This merge failure looks unhappy!

2021-03-12 21:15 UTC, davidby-influx commented on flux/control/controller.go
> +=======
Merge failure?

2021-03-12 21:15 UTC, davidby-influx commented on flux/control/controller.go
> +>>>>>>> 25fb1077e2... fix(flux): add durations to Flux logging (#19697)
Merge failure?

2021-03-12 21:39 UTC, lesam commented
Oops, missed a merge conflict. Fixed now.

2021-03-15 12:52 UTC, lesam commented
And fixed a stale test too

2021-03-15 16:09 UTC, davidby-influx approved these changes
LGTM

2021-03-15 16:33 UTC, merged