feat: error out when config file contains invalid options
influxdata/influxdb pull request #22996
Opened 2021-12-14 21:00 UTC by wbaker85

Closes #22863

Throws an error on server startup if there are values in the config file which do not correspond to a valid configuration option. Also adds debug logging if a config file is loaded.

2021-12-14 21:02 UTC, wbaker85 commented
Example when starting the server with a bad config value - `bind-address` used instead of `http-bind-address`:

```
./bin/darwin/influxd
error: unknown flags from config file at /Users/wbaker/influxdb/cmd/influxd/config.toml (see https://docs.influxdata.com/influxdb/latest/reference/config-options/ for supported flags): bind-address
```

If a full 1.x config is used, there will be many invalid options:

```
./bin/darwin/influxd
error: unknown flags from config file at /Users/wbaker/influxdb/cmd/influxd/config.toml (see https://docs.influxdata.com/influxdb/latest/reference/config-options/ for supported flags): coordinator.max-select-buckets,logging.level,http.flux-log-enabled,http.pprof-auth-enabled,http.ping-auth-enabled,http.pprof-enabled,coordinator.write-timeout,data.compact-throughput,http.bind-socket,http.auth-enabled,subscriber.write-concurrency,data.trace-logging-enabled,data.compact-throughput-burst,http.max-row-limit,coordinator.max-select-series,logging.suppress-logo,subscriber.http-timeout,tls.max-version,monitor.store-database,data.tsm-use-madv-willneed,udp,opentsdb,http.realm,http.bind-address,monitor.store-enabled,data.series-id-set-cache-size,data.wal-dir,data.cache-max-memory-size,data.cache-snapshot-memory-size,http.prom-read-auth-enabled,http.max-connection-limit,coordinator.log-queries-after,coordinator.max-concurrent-queries,monitor.store-interval,data.max-concurrent-compactions,data.series-file-max-concurrent-snapshot-compactions,continuous_queries.enabled,http.flux-enabled,data.dir,data.index-version,data.max-index-log-file-size,continuous_queries.run-interval,http.https-private-key,http.write-tracing,data.max-series-per-database,data.strict-error-handling,data.max-values-per-tag,data.cache-snapshot-write-cold-duration,meta.logging-enabled,http.unix-socket-enabled,http.https-enabled,bind-address,coordinator.max-select-point,logging.format,subscriber.enabled,data.validate-keys,shard-precreation.enabled,shard-precreation.check-interval,retention.enabled,meta.retention-autocreate,graphite,http.log-enabled,http.max-enqueued-write-limit,coordinator.query-timeout,http.enqueued-write-timeout,tls.min-version,subscriber.write-buffer-size,collectd,http.unix-socket-permissions,http.max-body-size,subscriber.ca-certs,retention.check-interval,subscriber.insecure-skip-verify,continuous_queries.log-enabled,http.debug-pprof-enabled,http.max-concurrent-write-limit,http.access-log-path,http.enabled,shard-precreation.advance-period,data.wal-fsync-delay,data.compact-full-write-cold-duration,continuous_queries.query-stats-enabled,meta.dir,http.suppress-write-log,http.shared-secret,http.https-certificate,data.query-log-enabled
```

2021-12-14 22:32 UTC, lesam requested changes
We should think some more about how this affects upgrades and rollbacks where the config changes.

2021-12-14 23:10 UTC, wbaker85 commented
Updated to check specifically for 1.x config values (and only 1.x config values).

2021-12-15 15:57 UTC, wbaker85 commented on cmd/influxd/launcher/cmd_test.go
> +			config: "bind-address: value\nmeta.something: value",
Yeah, probably makes more sense to use those more directly now that this is specifically looking for 1x config values. Updated the tests to be more along those lines.

2021-12-15 16:49 UTC, lesam approved these changes
Thanks!

2021-12-16 02:57 UTC, merged