build: bigger stack for musl builds
influxdata/influxdb pull request #23043
Opened 2022-01-06 20:31 UTC by docmerlin

2022-01-06 21:03 UTC, davidby-influx requested changes
Indentation...

2022-01-06 21:04 UTC, docmerlin commented
I think I fixed the indentation.

2022-01-06 21:08 UTC, davidby-influx commented on releng/raw-binaries/fs/usr/local/bin/influxdb_raw_binaries.bash
> +			echo go build $RACE_FLAG -o "$OUTDIR/$(basename $cmd)" -tags "netgo osusergo static_build" -ldflags="-s -extldflags \"-fno-PIC -Wl,-z,stack-size=8388608\"" $cmd
Why is this a static build?

2022-01-07 00:03 UTC, davidby-influx approved these changes
LGTM

2022-01-07 18:33 UTC, merged