feat(security): set SameSite=strict on session cookie
influxdata/influxdb pull request #23723
Opened 2022-09-12 20:23 UTC by jdstrand

Use `SameSite=Strict` as a hardening measure against cross-origin attacks. While browsers have been moving to default to `SameSite=Lax`, explicitly setting `SameSite` ensures that all browsers enforce it consistently. While `lax` is a reasonable hardening choice, the cookie is only required for requests to `/api/...` and we don't expect 3rd party links into `/api/...`, so this stricter setting should be safe in terms of usability. Furthermore, while our `GET` APIs are not state-changing, using 'strict' future-proofs us in case we add a state-changing `GET` API (`lax` allows cross-origin `GET` requests for increased usability for read-only requests).

Also add a comment to `SetCORS()` lack of `Access-Control-Allow-Credentials` as a reminder that its omission is intentional for defense in depth on when to attach the cookie to a request.

2022-09-12 22:33 UTC, jdstrand commented
@DStrand1 and @jeffreyssmith2nd - fyi, as a confidence builder, Cloud 2 uses `SameSite=strict` in its main session code for the entire API (not just `/api/` (it has other APIs beside `/api/...` that might need the session cookie).

2022-09-14 13:11 UTC, jeffreyssmith2nd approved these changes
Checked with session auth in influx-cli, lgtm 👍

2022-09-14 15:12 UTC, jeffreyssmith2nd requested changes
Actually let's hold off on this for a bit, I ran into some oddities when using influx v1 commands while on this branch. I will investigate and get back to you.

2022-09-14 15:25 UTC, jdstrand commented
> Actually let's hold off on this for a bit, I ran into some oddities when using influx v1 commands while on this branch. I will investigate and get back to you.

No worries. I would be quite surprised if the branch changed anything wrt to the CLI as Cloud 2 is already using `SameSite=Strict`, not to mention, I would expect the `influx` command to implement `SameSite` enforcement at all. Perhaps it would make sense to apply this on top of the 2.4 tag and try again? I'm also happy to help investigate.

2022-09-15 13:55 UTC, jeffreyssmith2nd approved these changes
Retested and couldn't reproduce, assuming it was user error/bad state.

2022-09-15 16:27 UTC, DStrand1 approved these changes
LGTM as well, couldn't find any issues!

2022-09-15 20:30 UTC, jdstrand commented
> Retested and couldn't reproduce, assuming it was user error/bad state.

I decided to also take a lot at the new 2.4 `--username-password` session auth and verified that everything works ok with this (indeed, on every API request, the `influx` command is hitting the `/api/v2/signin` endpoint with BasicAuth to obtain a cookie that is attached to the request for the command the user specified. The `influx` command isn't doing anything with SOP, CORS, SameSite, etc (but it doesn't have to) and is expected to (and did) work fine with this change).

2022-09-15 20:30 UTC, merged

2022-09-15 20:30 UTC, jdstrand commented
@jeffreyssmith2nd and @DStrand1 - thanks for the reviews!